### ISSUE TITLE
./bin/setup & lsc: command not found

### ISSUE THREAD

**Issue by infertux** [whilelse/whilelse#1]
`./bin/setup` doesn't check for errors during the installation process and I was left with the impression that the script succeeded with a zero exit code while in fact there was an error about `lsc` buried in the output. So I changed the script to fail early if it encounters an error:

``` diff
diff --git i/bin/setup w/bin/setup
index 07f3209..90497ec 100755
--- i/bin/setup
+++ w/bin/setup
@@ -1,6 +1,11 @@
-( cd frontend && npm install )
-( cd ploy && bundle install )
-( cd async-convert && npm install && lsc -co gen src )
-( cd store && bundle install && npm install && lsc -co gen src )
+#!/bin/bash -eux

+pushd frontend && npm install
+popd
+pushd ploy && bundle install
+popd
+pushd async-convert && npm install && lsc -co gen src
+popd
+pushd store && bundle install && npm install && lsc -co gen src
+popd
```

(I can send you a patch or PR if you're interested.)

Running `./bin/setup` again led to this:

```
[...]
+ pushd async-convert
~/dev/whilelse/async-convert ~/dev/whilelse
+ npm install
npm WARN async@0.0.1 No repository field.
+ lsc -co gen src
./bin/setup: line 7: lsc: command not found
zsh: exit 127   ./bin/setup
```

So I changed `lsc` to `../frontend/node_modules/.bin/lsc` in `bin/setup` and the script ran successfully.

However I think the proper solution is to have `lsc` in the `$PATH` ideally because otherwise I get the same issue when running `./bin/run`:

```
2016-03-24 07:23:04,242 INFO RPC interface 'supervisor' initialized
2016-03-24 07:23:04,242 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-03-24 07:23:04,242 INFO supervisord started with pid 8679
2016-03-24 07:23:05,243 INFO spawnerr: can't find command 'lsc'
2016-03-24 07:23:05,244 INFO spawnerr: can't find command 'brunch'
[...]
```

I don't use `npm` much so I'm not sure what's the best approach here and whether installing `lsc` globally is a good idea.

**Comment by bagilevi** [comment]
Thanks a lot. Feel free to send a PR with your changes.
